### ISSUE TITLE
Error:  bot.models.User.DoesNotExist

### ISSUE THREAD

**Issue by torresfabian** [The-Judge/python_telegram_bot#1]
**Spanish**

Estimado Marc, en primer lugar quiero agradecerte el gran tutorial que hiciste y que fue de gran ayuda para comprender como realizar un bot de telegram.

Fui escribiendo el código con cada capítulo y me encontré con el error  "bot.models.User.DoesNotExist". Pensé que me equivoqué en algo y cloné el proyecto desde github y me sigue apareciendo el mismo error.

Agradecería cualquier pista para solucionar este inconveniente.

**English**

Dear Marc, first of all I want to thank you for the great tutorial that you did and that was of great help to understand how to make a telegram bot.

I was writing the code with each chapter and I found the error "bot.models.User.DoesNotExist". I thought I was wrong about something and I cloned the project from github and I keep getting the same error.

I would appreciate any clues to solve this problem.

**German**

Lieber Marc, zunächst möchte ich dir für das tolle Tutorial danken, das du gemacht hast und das war eine große Hilfe, um zu verstehen, wie man einen Telegramm-Bot erstellt.

Ich habe den Code mit jedem Kapitel geschrieben und den Fehler "bot.models.User.DoesNotExist" gefunden. Ich dachte, ich hätte etwas falsch gemacht und ich habe das Projekt von github geklont und erhalte immer wieder den gleichen Fehler.

Ich würde mich über Hinweise zur Lösung dieses Problems freuen.

**** pip list: ****

pip list
Package           Version
----------------- -----------
aiohttp           3.7.4.post0
asgiref           3.4.1
async-timeout     3.0.1
attrs             21.2.0
chardet           4.0.0
Django            2.1
idna              3.2
idna-ssl          1.1.0
multidict         5.1.0
pip               21.1.3
pytz              2021.1
setuptools        57.0.0
sqlparse          0.4.1
telepot           12.7
typing-extensions 3.10.0.0
urllib3           1.26.6
wheel             0.36.2
yarl              1.6.3

**** terminal *****

Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
July 08, 2021 - 02:41:32
Django version 3.2.5, using settings 'dtbot.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Internal Server Error: /bot/hook/
Traceback (most recent call last):
  File "/PRUEBAS/bot_telegram_orig/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/PRUEBAS/bot_telegram_orig/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/PRUEBAS/bot_telegram_orig/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/PRUEBAS/bot_telegram_orig/python_telegram_bot/bot/views.py", line 77, in talkin_to_me_bruh
    result = _add_message_to_db(json_message)
  File "/PRUEBAS/bot_telegram_orig/python_telegram_bot/bot/views.py", line 50, in _add_message_to_db
    sender_object = User.objects.filter(user_id__exact=sender_id).get()
  File "/PRUEBAS/bot_telegram_orig/env/lib/python3.6/site-packages/django/db/models/query.py", line 437, in get
    self.model._meta.object_name
bot.models.User.DoesNotExist: User matching query does not exist.
[08/Jul/2021 02:41:44] "POST /bot/hook/ HTTP/1.1" 500 75305

**Comment by torresfabian** [comment]
Me respondo a mi mismo y cierro el problema. El inconveniente ocurrió porque intente correr el código sin haber creado el usuario en la base de datos, dentro de app bot.

**Comment by The-Judge** [comment]
Dear @torresfabian ,

I can't reproduce this, honestly:

```
/Users/mrichter/Development
Development $ git clone https://github.com/The-Judge/python_telegram_bot.git
Cloning into 'python_telegram_bot'...
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 74 (delta 30), reused 70 (delta 28), pack-reused 0
Receiving objects: 100% (74/74), 17.01 KiB | 3.40 MiB/s, done.
Resolving deltas: 100% (30/30), done.
[last: 0s] [exit: 0] mrichter 14:59:15 (CEST) Thu 2021-07-15
/Users/mrichter/Development
Development $ cd python_telegram_bot/
[last: 0s] [exit: 0] mrichter 14:59:21 (CEST) Thu 2021-07-15
/Users/mrichter/Development/python_telegram_bot
python_telegram_bot $ pipenv-activate
(python_telegram_bot) [last: 1s] [exit: 0] mrichter 14:59:29 (CEST) Thu 2021-07-15
/Users/mrichter/Development/python_telegram_bot
python_telegram_bot $ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, bot, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying bot.0001_initial... OK
  Applying bot.0002_message... OK
  Applying sessions.0001_initial... OK
(python_telegram_bot) [last: 0s] [exit: 0] mrichter 14:59:37 (CEST) Thu 2021-07-15
/Users/mrichter/Development/python_telegram_bot
python_telegram_bot $ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
July 15, 2021 - 12:59:44
Django version 2.1, using settings 'dtbot.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
^C(python_telegram_bot) [last: 108s] [exit: 0] mrichter 15:01:32 (CEST) Thu 2021-07-15
/Users/mrichter/Development/python_telegram_bot
python_telegram_bot $ python -V
Python 3.6.14
(python_telegram_bot) [last: 0s] [exit: 0] mrichter 15:01:35 (CEST) Thu 2021-07-15
/Users/mrichter/Development/python_telegram_bot
python_telegram_bot $
```

Please provide more details (in English please) on what you are doing with the provided code, exactly.

**Comment by The-Judge** [comment]
~2 weeks no reply - assuming issue has been resolved.
